algoritmo "semnome"
// Função :
// Autor :
// Data : 31/08/2020
// Seção de Declarações 
var
n,m : inteiro
inicio
// Seção de Comandos 
escreval("escolha um número para começar sua sequencia")
leia(n)
escreval("escreva o número final de sua sequencia")
leia(m)
se (m<=n) entao
escreval ("numero invalido, tente outro")
senao
para n de n ate m passo 1 faca
escreval(n)
fimpara
fimse

fimalgoritmo
